### ISSUE TITLE
ISSUE-2664: PIP-31: Transactional Streaming

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#106]
Original Issue: apache/pulsar#2664 

---

This is the master issue for tracking implementing PIP-31: https://docs.google.com/document/d/145VYp09JKTw9jAT-7yNyFU255FptB2_B2Fye100ZXDI/edit#heading=h.40v9f3564x7t

The PIP is broken down into following tasks:

- [x] API change #4161 #4165 #4952
- [x] Protocol change #4866 #4776
- [x] Transaction buffer
   - [x] In-memory transaction buffer #4165 
   - [x] Persistent transaction buffer  #4738
   - [x] Transaction buffer client #6544
- [x] Transaction coordinator
   - [x] In-memory transaction coordinator #4161
   - [ ] Persistent transaction coordinator #5570
   - [x] Transaction coordinator assignment(TC startup and failover) #5515
   - [x] Transaction coordinator client #5680
- [x] Transacdtional Acknowledgement
   - [x] Introduce PENDING_ACK state in acknowledgement path #4265
   - [ ] Persistence of pending acks #4557
- [ ] Transaction request handling in the broker: implementation of the request in broker side.
- [ ] Handle committed transaction
   - [ ] Offloader
   - [ ] TopicCompaction (add integration test to confirm)
   - [ ] Presto (optional for first version)
- [ ] Client and broker integration
- [ ] Functions: Make functions use transactions
- [ ] Integration Tests 
- [ ] Chaos (Jepsen) Tests

--- 

(Before 10/01)

- [x] End to end logic is done (09/07)
- [x] Support produce transaction batch messages
- [ ] pending acks
- [ ] integration tests (streamnative/pulsar#1311) (09/17)
- [x] Integration tests added (09/10)
- [ ] ~~Persistence + Recovery (09/24)~~ new transaction buffer don't need to persistent and recover
- [ ] ~~Transaction buffer data cleanup~~ new transaction buffer don't need to cleanup
--- 

pending messages filter - TBD

messages in the pending-ack state should be filtered when sending to consumers.

---

- [x] pulsar client
   - [x] expose transaction api https://github.com/apache/pulsar/pull/8505
   - [x] register transaction metadata fix https://github.com/apache/pulsar/pull/8493
   - [x] transaction metadata handlers connect guarantee https://github.com/apache/pulsar/pull/8563
- [x] transaction buffer
   - [x] transaction buffer refactor https://github.com/apache/pulsar/pull/8347
   - [x] transaction buffer interface adjust https://github.com/apache/pulsar/pull/8291
- [x] transaction message
   - [x] produce batch transaction messages https://github.com/apache/pulsar/pull/8415
   - [x] prodcue transaction messages in sync way https://github.com/apache/pulsar/pull/8631
- [x] transaction commit
   - [x] commit on topic partition https://github.com/apache/pulsar/pull/7552
   - [x] commit on subscription https://github.com/apache/pulsar/pull/7856
   - [x] abort on topic partition https://github.com/apache/pulsar/pull/7953
   - [x] abort on subscription https://github.com/apache/pulsar/pull/8291
- [x] pending-ack state related
   - [x] pending-ack process https://github.com/apache/pulsar/pull/8426
- [x] cleanup
   - [x] transaction marker clear https://github.com/apache/pulsar/pull/8318
- [x] integration test https://github.com/apache/pulsar/pull/8594
