### ISSUE TITLE
ISSUE-4077: PIP-34 New subscription type Key_Shared

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#32]
Original Issue: apache/pulsar#4077 

---

There are many aspects to be covered for [PIP-34](https://github.com/apache/pulsar/wiki/PIP-34%3A-Add-new-subscribe-type-Key_Failover), this is a task list tracker for this PIP

**Tasks**

- [x] Core implementation #4079
- [x] Broker level flag to enable or disable this feature #4120
- [x] Integration tests #4352
- [x] Non persistent dispatcher #4462
- [x] Documentation  #4079
- [ ] Subscription level consumer selector setting.
- [ ] Client CLI
- [ ] Policy specify without message key
- [x] Batch message #4435
- [ ] Consumer priority
- [x] Redelivery ordering guarantee #4406 
- [ ] dispatch messages to new consumer after exist consumer ack all messages dispatched
- [ ] send hash ring change events to consumers 
- [x] Reader support for sticky key range [#5928]
- [ ] Expose key shared consumer selector range in API [#5752]
