### ISSUE TITLE
ISSUE-17302: Tracking Issue for multilingual clients document catching up

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#4792]
Original Issue: apache/pulsar#17302 

---

### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We have a [Client Libraries](https://pulsar.apache.org/docs/next/client-libraries) page to host all official client libraries documents. Despite the Java client's document being relatively completed, documents for multilingual clients are outdated and less maintained.

This issue tracks the effort to document what we already implemented for multilingual clients, focusing on the C++ client, the Python client, and the Node.js client - all based on the core C++ client library.

### Solution

The catching-up plan is based on:

1. [Java client's document](https://pulsar.apache.org/docs/next/client-libraries-java) for the overall structure.
2. [Feature Matrix](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914) for what we already implemented.

#### Layout

Top-level layout (continuously updating):

* Brief introducation
* Installation
* Connection URLs
* Client
* Producer
* Consumer
* Reader
* Table View
* Schema
* Authentication

#### Common

* [ ] #17303
* [ ] #17307

#### C++

* [ ] Simplify the Install section and promote a top-level "Install" title

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!
