### ISSUE TITLE
ISSUE-17495: [Doc] Tracking issue for incorrect contents and links

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#4838]
Original Issue: apache/pulsar#17495 

---

### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When I go through the document of Pulsar, I found some contents are wrong, outdated, or incomplete, and some links are incorrect or broken.

### What is your suggestion?

It happens that I have some time to work on these issues. Although, handling issues can take more time than spotting issues. 

I'd prefer to create this tracking issue for all related contents or links so all contributors can align on the current status and possibly take over some tasks.

### Contents

* [ ] If you follow the [getting-started-standalone](https://pulsar.apache.org/docs/2.9.x/getting-started-standalone/) page, you won't see any message consumed because it suggests you run consume before producing a message and say that you should get a message consumed. This wart should be resolved by #17475.
* [ ] Pulsar SQL document is outdated since we bump PrestoSQL version to Trino version
* [ ] Pulsar SQL section has a confusing [Query Your Own Data](https://pulsar.apache.org/docs/next/sql-getting-started#query-your-own-data) code snippet without any instructions.

### Links

* [ ] [/tools/pulsar-client](https://pulsar.apache.org/tools/pulsar-client/) displays confusing content, ditto [/tools/pulsar-admin](https://pulsar.apache.org/tools/pulsar-admin)
* [ ] `/api/cpp` in content rendered to SNAPSHOT document. For example, Pulsar Python client has [a link to SNAPSHOT document](https://github.com/apache/pulsar/blob/a7f1a5657782ff7ac91a89afdd49568d74d111f5/site2/docs/client-libraries-python.md?plain=1#L13)
* [ ] `/reference-configuration` should not hold [a hard link](https://github.com/apache/pulsar/blob/a7f1a5657782ff7ac91a89afdd49568d74d111f5/site2/docs/reference-configuration.md?plain=1#L9) to https://pulsar.apache.org/reference, it should use `/reference` to decouple with `baseDir`.
