### ISSUE TITLE
ISSUE-18144: Tracking issue for Archive Ancient (Incubating) Documents

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#5020]
Original Issue: apache/pulsar#18144 

---

### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

I noticed that we write a lot of logic to handle ancient documents back to the incubating period on the current doc site syncing and building. It causes unnecessary maintenance burdens as well as more broken links due to different document frameworks.

### What is your suggestion?

Since those ancient documents have lower visits and most importantly, we should not make any changes to them, I propose:

- [ ] #18145
- [ ] Remove https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs/xxx-incubating.
- [ ] Remove build logic about those pages.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!
