### ISSUE TITLE
ISSUE-19064: Tracking Issue for Moving Source of Docs to the Site Repo

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#5314]
Original Issue: apache/pulsar#19064 

---

### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Mailing thread: https://lists.apache.org/thread/89wl112cflvtoyfg3l7kglr1dozsljm9

### What is your suggestion?

1. Move the website's content to the root level, then we have a first-class Docu&yarn-based JS project layout. It's more convenient and familiar to related developers.
2. Host the source of docs in the site repo (apache/pulsar-site) instead of under `site2` folder in the main repo and do content sync.

* [ ] Migrate build site scripts to pytools
* [ ] Stop sync docs from the main repo
* [ ] Remove docs from the main repo
* [ ] Lift site folder to the top level
* [ ] Add build stage without push in the site pre-commit workflow

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!
